# fly.toml app configuration file generated for pqvkbot on 2023-05-11T06:03:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pqvkbot"
primary_region = "arn"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
